// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgahlpsipxiokkkppgci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnYWhscHNpcHhpb2tra3BwZ2NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNDE4NTksImV4cCI6MjA3MzkxNzg1OX0.zyyNoh97KizW_dRYcUcVnT9-Ry_ZAxnpekn66JXDj0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});